-- MySQL Script generated by MySQL Workbench
-- Fri Jun 21 15:54:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Estoque
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Estoque` ;

-- -----------------------------------------------------
-- Schema Estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Estoque` DEFAULT CHARACTER SET utf8 ;
USE `Estoque` ;

-- -----------------------------------------------------
-- Table `Estoque`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estoque`.`categoria` ;

CREATE TABLE IF NOT EXISTS `Estoque`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estoque`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estoque`.`produto` ;

CREATE TABLE IF NOT EXISTS `Estoque`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `preco_custo` DECIMAL(9,2) NOT NULL,
  `preco_venda` DECIMAL(9,2) NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `unidade_medida` CHAR(2) NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categoria_id`),
  INDEX `fk_produto_categoria_idx` (`categoria_id` ASC) ,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `Estoque`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
